CREATE DATABASE IF NOT EXISTS traffic_safety;
USE traffic_safety;

DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS crashes;

CREATE TABLE crashes (
    st_case INT PRIMARY KEY,
    state INT NOT NULL,
    statename VARCHAR(100),
    county INT,
    countyname VARCHAR(150),
    city INT,
    cityname VARCHAR(150),
    month INT,
    monthname VARCHAR(50),
    day INT,
    dayname VARCHAR(50),
    day_week INT,
    day_weekname VARCHAR(50),
    year INT NOT NULL,
    hour INT,
    minute INT,
    tway_id VARCHAR(150),
    route INT,
    rur_urb INT,
    rur_urbname VARCHAR(100),
    func_sys INT,
    func_sysname VARCHAR(150),
    latitude DECIMAL(10, 7),
    longitud DECIMAL(10, 7),
    harm_ev INT,
    harm_evname VARCHAR(255),
    man_coll INT,
    man_collname VARCHAR(255),
    reljct1 INT,
    reljct1name VARCHAR(255),
    reljct2 INT,
    reljct2name VARCHAR(255),
    typ_int INT,
    typ_intname VARCHAR(255),
    rel_road INT,
    rel_roadname VARCHAR(255),
    wrk_zone INT,
    wrk_zonename VARCHAR(255),
    lgt_cond INT,
    lgt_condname VARCHAR(255),
    weather INT,
    weathername VARCHAR(255),
    fatals INT NOT NULL DEFAULT 1,
    INDEX idx_crashes_state (state),
    INDEX idx_crashes_year (year)
);

CREATE TABLE vehicles (
    st_case INT NOT NULL,
    veh_no INT NOT NULL,
    state INT NOT NULL,
    numoccs INT,
    hit_run INT,
    mod_year INT,
    makename VARCHAR(150),
    model INT,
    body_typname VARCHAR(150),
    rollover INT,
    trav_sp INT,
    speedrel INT,
    speedrelname VARCHAR(255),
    dr_drink INT,
    dr_drinkname VARCHAR(100),
    dr_pres INT,
    dr_presname VARCHAR(100),
    vtrafway INT,
    vtrafwayname VARCHAR(150),
    vnum_lan INT,
    vspd_lim INT,
    valign INT,
    vprofile INT,
    vpavetyp INT,
    vsurcond INT,
    vtrafcon INT,
    p_crash1 INT,
    p_crash1name VARCHAR(255),
    acc_type INT,
    acc_typename VARCHAR(255),
    deaths INT NOT NULL DEFAULT 0,
    PRIMARY KEY (st_case, veh_no),
    CONSTRAINT fk_vehicles_crashes FOREIGN KEY (st_case) 
        REFERENCES crashes (st_case) ON DELETE CASCADE
);

CREATE TABLE people (
    st_case INT NOT NULL,
    veh_no INT NOT NULL,
    per_no INT NOT NULL,
    state INT NOT NULL,
    age INT,
    sex INT,
    sexname VARCHAR(50),
    per_typ INT,
    per_typname VARCHAR(150),
    inj_sev INT,
    inj_sevname VARCHAR(150),
    seat_pos INT,
    seat_posname VARCHAR(150),
    rest_use INT,
    rest_usename VARCHAR(150),
    helm_use INT,
    helm_usename VARCHAR(150),
    air_bag INT,
    air_bagname VARCHAR(150),
    ejection INT,
    ejectionname VARCHAR(150),
    drinking INT,
    drinkingname VARCHAR(100),
    alc_status INT,
    alc_statusname VARCHAR(100),
    drugs INT,
    drugsname VARCHAR(100),
    hospital INT,
    hospitalname VARCHAR(150),
    doa INT,
    doaname VARCHAR(100),
    PRIMARY KEY (st_case, veh_no, per_no),
    CONSTRAINT fk_people_crashes FOREIGN KEY (st_case) 
        REFERENCES crashes (st_case) ON DELETE CASCADE
);